name: RP2040 tests

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  test-elf:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out source
        uses: actions/checkout@v4

      - name: Install Arm GNU toolchain
        uses: carlosperate/arm-none-eabi-gcc-action@v1
        with:
          release: 13.2.Rel1

      - name: Configure test ELF
        run: >-
          cmake -S . -B build
          -DCMAKE_BUILD_TYPE=Debug
          -DPICO_SIMULATOR=ON

      - name: Build test ELF
        run: cmake --build build --target mytest --parallel

      - name: Run test ELF in a simulated Raspberry Pi Pico
        uses: wokwi/wokwi-ci-action@v1
        with:
          token: ${{ secrets.WOKWI_CLI_TOKEN }}
          path: /
          timeout: 12000
          expect_text: 2 Tests 0 Failures 0 Ignored
          fail_text: FAIL
          serial_log_file: wokwi-serial.log

      - name: Upload simulator serial log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: wokwi-serial-log
          path: wokwi-serial.log
          if-no-files-found: ignore
